server:
  port: 7788

info:
  component: citijpa

logging:
  file: citijpa.log

hystrix:
  threadpool:
    default:
      coreSize: 350
      maximumSize: 350
      maxQueueSize: -1
      queueSizeRejectionThreshold: 20
      allowMaximumSizeToDivergeFromCoreSize: true

feign:
  hystrix:
    enabled: true

